server:
  port: 22301
  shutdown: graceful


spring:
  profiles:
    active: local
  application:
    name: lck-eureka
  security:
    user:
      name: admin
      password: $2a$10$BVhva6MLZ0HviRX4c/L1I.nOuN86IWdfP7eA2vyQFjs1Eyw5.YyY6